version: "2"

services:
  app:
    build: .
    environment:
      - NODE_ENV=production
      - DB_HOST=mariadb
      - DB_PASS=floatbehind_pwd
      - REDIS_HOST=redis
      - SERVICE_HOST=http://localhost:3000
      - SLACK_CLIENT_ID=[YOUR_SLACK_CLIENT_ID]
      - SLACK_CLIENT_SECRET=[YOUR_SLACK_CLIENT_SECRET]
    expose:
      - "3000"
    ports:
      - "3000:3000"
    links:
      - mariadb
      - redis
  mariadb:
    # Run setup/init.sql at first!!
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    image: "mariadb:10.1.2"
    environment:
        - MYSQL_ROOT_PASSWORD=password
  redis:
    image: "redis:3.2"
